#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web01 and web02 servers 
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 464274-web-01 54.234.78.57:80 check
   server 464274-web-02 54.227.224.108:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
